//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\pratapa.ADS\source\repos\LlvmDSCompiler\LlvmDSCompiler\DesignScript.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace LlvmDSCompiler {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IDesignScriptListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public partial class DesignScriptBaseListener : IDesignScriptListener {
	/// <summary>
	/// Enter a parse tree produced by the <c>primaryExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimaryExpr([NotNull] DesignScriptParser.PrimaryExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>primaryExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimaryExpr([NotNull] DesignScriptParser.PrimaryExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>indexExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexExpr([NotNull] DesignScriptParser.IndexExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>indexExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexExpr([NotNull] DesignScriptParser.IndexExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>repGuideExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRepGuideExpr([NotNull] DesignScriptParser.RepGuideExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>repGuideExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRepGuideExpr([NotNull] DesignScriptParser.RepGuideExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>atLevelExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtLevelExpr([NotNull] DesignScriptParser.AtLevelExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>atLevelExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtLevelExpr([NotNull] DesignScriptParser.AtLevelExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>funcCallExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncCallExpr([NotNull] DesignScriptParser.FuncCallExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>funcCallExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncCallExpr([NotNull] DesignScriptParser.FuncCallExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>fieldExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldExpr([NotNull] DesignScriptParser.FieldExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>fieldExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldExpr([NotNull] DesignScriptParser.FieldExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>unaryExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryExpr([NotNull] DesignScriptParser.UnaryExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>unaryExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryExpr([NotNull] DesignScriptParser.UnaryExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>mulDivModExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMulDivModExpr([NotNull] DesignScriptParser.MulDivModExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>mulDivModExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMulDivModExpr([NotNull] DesignScriptParser.MulDivModExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>addSubExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddSubExpr([NotNull] DesignScriptParser.AddSubExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>addSubExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddSubExpr([NotNull] DesignScriptParser.AddSubExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>compExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompExpr([NotNull] DesignScriptParser.CompExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>compExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompExpr([NotNull] DesignScriptParser.CompExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>eqExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqExpr([NotNull] DesignScriptParser.EqExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>eqExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqExpr([NotNull] DesignScriptParser.EqExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>andExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndExpr([NotNull] DesignScriptParser.AndExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>andExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndExpr([NotNull] DesignScriptParser.AndExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>orExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrExpr([NotNull] DesignScriptParser.OrExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>orExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrExpr([NotNull] DesignScriptParser.OrExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>triRangeExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTriRangeExpr([NotNull] DesignScriptParser.TriRangeExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>triRangeExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTriRangeExpr([NotNull] DesignScriptParser.TriRangeExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>unitRangeExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnitRangeExpr([NotNull] DesignScriptParser.UnitRangeExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>unitRangeExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnitRangeExpr([NotNull] DesignScriptParser.UnitRangeExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>inlineConditionExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInlineConditionExpr([NotNull] DesignScriptParser.InlineConditionExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>inlineConditionExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInlineConditionExpr([NotNull] DesignScriptParser.InlineConditionExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>parenExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenExpr([NotNull] DesignScriptParser.ParenExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>parenExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenExpr([NotNull] DesignScriptParser.ParenExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>litExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLitExpr([NotNull] DesignScriptParser.LitExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>litExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLitExpr([NotNull] DesignScriptParser.LitExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>ident</c>
	/// labeled alternative in <see cref="DesignScriptParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdent([NotNull] DesignScriptParser.IdentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ident</c>
	/// labeled alternative in <see cref="DesignScriptParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdent([NotNull] DesignScriptParser.IdentContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>doubleLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDoubleLit([NotNull] DesignScriptParser.DoubleLitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>doubleLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDoubleLit([NotNull] DesignScriptParser.DoubleLitContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>intLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntLit([NotNull] DesignScriptParser.IntLitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>intLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntLit([NotNull] DesignScriptParser.IntLitContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>stringLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringLit([NotNull] DesignScriptParser.StringLitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>stringLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringLit([NotNull] DesignScriptParser.StringLitContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>boolLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolLit([NotNull] DesignScriptParser.BoolLitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>boolLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolLit([NotNull] DesignScriptParser.BoolLitContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>nullLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullLit([NotNull] DesignScriptParser.NullLitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>nullLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullLit([NotNull] DesignScriptParser.NullLitContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>listLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListLit([NotNull] DesignScriptParser.ListLitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>listLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListLit([NotNull] DesignScriptParser.ListLitContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>dictLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDictLit([NotNull] DesignScriptParser.DictLitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>dictLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDictLit([NotNull] DesignScriptParser.DictLitContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>imperCoreStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImperCoreStmt([NotNull] DesignScriptParser.ImperCoreStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>imperCoreStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImperCoreStmt([NotNull] DesignScriptParser.ImperCoreStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>ifStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStmt([NotNull] DesignScriptParser.IfStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ifStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStmt([NotNull] DesignScriptParser.IfStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>forStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStmt([NotNull] DesignScriptParser.ForStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>forStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStmt([NotNull] DesignScriptParser.ForStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>whileStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStmt([NotNull] DesignScriptParser.WhileStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>whileStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStmt([NotNull] DesignScriptParser.WhileStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>breakStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreakStmt([NotNull] DesignScriptParser.BreakStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>breakStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreakStmt([NotNull] DesignScriptParser.BreakStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>continueStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContinueStmt([NotNull] DesignScriptParser.ContinueStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>continueStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContinueStmt([NotNull] DesignScriptParser.ContinueStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>blockStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockStmt([NotNull] DesignScriptParser.BlockStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>blockStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockStmt([NotNull] DesignScriptParser.BlockStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>typeNameArbitraryRank</c>
	/// labeled alternative in <see cref="DesignScriptParser.typeNameWithRank"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeNameArbitraryRank([NotNull] DesignScriptParser.TypeNameArbitraryRankContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>typeNameArbitraryRank</c>
	/// labeled alternative in <see cref="DesignScriptParser.typeNameWithRank"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeNameArbitraryRank([NotNull] DesignScriptParser.TypeNameArbitraryRankContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>typeNameRankOneOrMore</c>
	/// labeled alternative in <see cref="DesignScriptParser.typeNameWithRank"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeNameRankOneOrMore([NotNull] DesignScriptParser.TypeNameRankOneOrMoreContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>typeNameRankOneOrMore</c>
	/// labeled alternative in <see cref="DesignScriptParser.typeNameWithRank"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeNameRankOneOrMore([NotNull] DesignScriptParser.TypeNameRankOneOrMoreContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>typeNameRank</c>
	/// labeled alternative in <see cref="DesignScriptParser.typeNameWithRank"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeNameRank([NotNull] DesignScriptParser.TypeNameRankContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>typeNameRank</c>
	/// labeled alternative in <see cref="DesignScriptParser.typeNameWithRank"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeNameRank([NotNull] DesignScriptParser.TypeNameRankContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] DesignScriptParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] DesignScriptParser.ProgramContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.coreStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCoreStmt([NotNull] DesignScriptParser.CoreStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.coreStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCoreStmt([NotNull] DesignScriptParser.CoreStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.funcDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncDef([NotNull] DesignScriptParser.FuncDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.funcDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncDef([NotNull] DesignScriptParser.FuncDefContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.imperFuncDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImperFuncDef([NotNull] DesignScriptParser.ImperFuncDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.imperFuncDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImperFuncDef([NotNull] DesignScriptParser.ImperFuncDefContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.emptyStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmptyStmt([NotNull] DesignScriptParser.EmptyStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.emptyStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmptyStmt([NotNull] DesignScriptParser.EmptyStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.funcDefArgList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncDefArgList([NotNull] DesignScriptParser.FuncDefArgListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.funcDefArgList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncDefArgList([NotNull] DesignScriptParser.FuncDefArgListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.funcDefArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncDefArg([NotNull] DesignScriptParser.FuncDefArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.funcDefArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncDefArg([NotNull] DesignScriptParser.FuncDefArgContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] DesignScriptParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] DesignScriptParser.ExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary([NotNull] DesignScriptParser.PrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary([NotNull] DesignScriptParser.PrimaryContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.parExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParExpr([NotNull] DesignScriptParser.ParExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.parExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParExpr([NotNull] DesignScriptParser.ParExprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.lit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLit([NotNull] DesignScriptParser.LitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.lit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLit([NotNull] DesignScriptParser.LitContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.exprList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprList([NotNull] DesignScriptParser.ExprListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.exprList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprList([NotNull] DesignScriptParser.ExprListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.atLevel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtLevel([NotNull] DesignScriptParser.AtLevelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.atLevel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtLevel([NotNull] DesignScriptParser.AtLevelContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.repGuideList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRepGuideList([NotNull] DesignScriptParser.RepGuideListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.repGuideList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRepGuideList([NotNull] DesignScriptParser.RepGuideListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.exprStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprStmt([NotNull] DesignScriptParser.ExprStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.exprStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprStmt([NotNull] DesignScriptParser.ExprStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.returnStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStmt([NotNull] DesignScriptParser.ReturnStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.returnStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStmt([NotNull] DesignScriptParser.ReturnStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.imperAnnot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImperAnnot([NotNull] DesignScriptParser.ImperAnnotContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.imperAnnot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImperAnnot([NotNull] DesignScriptParser.ImperAnnotContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.imperBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImperBlock([NotNull] DesignScriptParser.ImperBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.imperBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImperBlock([NotNull] DesignScriptParser.ImperBlockContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.imperBlockReturnStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImperBlockReturnStmt([NotNull] DesignScriptParser.ImperBlockReturnStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.imperBlockReturnStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImperBlockReturnStmt([NotNull] DesignScriptParser.ImperBlockReturnStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.imperBlockAssignStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImperBlockAssignStmt([NotNull] DesignScriptParser.ImperBlockAssignStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.imperBlockAssignStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImperBlockAssignStmt([NotNull] DesignScriptParser.ImperBlockAssignStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.imperBlockBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImperBlockBody([NotNull] DesignScriptParser.ImperBlockBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.imperBlockBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImperBlockBody([NotNull] DesignScriptParser.ImperBlockBodyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.imperStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImperStmt([NotNull] DesignScriptParser.ImperStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.imperStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImperStmt([NotNull] DesignScriptParser.ImperStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.assignStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignStmt([NotNull] DesignScriptParser.AssignStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.assignStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignStmt([NotNull] DesignScriptParser.AssignStmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.typedIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypedIdent([NotNull] DesignScriptParser.TypedIdentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.typedIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypedIdent([NotNull] DesignScriptParser.TypedIdentContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.keyValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeyValue([NotNull] DesignScriptParser.KeyValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.keyValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeyValue([NotNull] DesignScriptParser.KeyValueContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.keyValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeyValues([NotNull] DesignScriptParser.KeyValuesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.keyValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeyValues([NotNull] DesignScriptParser.KeyValuesContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.typedIdentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypedIdentList([NotNull] DesignScriptParser.TypedIdentListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.typedIdentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypedIdentList([NotNull] DesignScriptParser.TypedIdentListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.identList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentList([NotNull] DesignScriptParser.IdentListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.identList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentList([NotNull] DesignScriptParser.IdentListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.qualifiedIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQualifiedIdent([NotNull] DesignScriptParser.QualifiedIdentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.qualifiedIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQualifiedIdent([NotNull] DesignScriptParser.QualifiedIdentContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.typeNameWithRank"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeNameWithRank([NotNull] DesignScriptParser.TypeNameWithRankContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.typeNameWithRank"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeNameWithRank([NotNull] DesignScriptParser.TypeNameWithRankContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeName([NotNull] DesignScriptParser.TypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeName([NotNull] DesignScriptParser.TypeNameContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace LlvmDSCompiler
