//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\pratapa.ADS\source\repos\LlvmDSCompiler\LlvmDSCompiler\DesignScript.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace LlvmDSCompiler {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="DesignScriptParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public interface IDesignScriptListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by the <c>primaryExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpr([NotNull] DesignScriptParser.PrimaryExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>primaryExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpr([NotNull] DesignScriptParser.PrimaryExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>indexExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexExpr([NotNull] DesignScriptParser.IndexExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>indexExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexExpr([NotNull] DesignScriptParser.IndexExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>repGuideExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepGuideExpr([NotNull] DesignScriptParser.RepGuideExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>repGuideExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepGuideExpr([NotNull] DesignScriptParser.RepGuideExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>atLevelExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtLevelExpr([NotNull] DesignScriptParser.AtLevelExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>atLevelExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtLevelExpr([NotNull] DesignScriptParser.AtLevelExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>funcCallExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncCallExpr([NotNull] DesignScriptParser.FuncCallExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>funcCallExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncCallExpr([NotNull] DesignScriptParser.FuncCallExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>fieldExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldExpr([NotNull] DesignScriptParser.FieldExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>fieldExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldExpr([NotNull] DesignScriptParser.FieldExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>unaryExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpr([NotNull] DesignScriptParser.UnaryExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>unaryExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpr([NotNull] DesignScriptParser.UnaryExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>mulDivModExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulDivModExpr([NotNull] DesignScriptParser.MulDivModExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>mulDivModExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulDivModExpr([NotNull] DesignScriptParser.MulDivModExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>addSubExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddSubExpr([NotNull] DesignScriptParser.AddSubExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>addSubExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddSubExpr([NotNull] DesignScriptParser.AddSubExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>compExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompExpr([NotNull] DesignScriptParser.CompExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>compExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompExpr([NotNull] DesignScriptParser.CompExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>eqExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqExpr([NotNull] DesignScriptParser.EqExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>eqExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqExpr([NotNull] DesignScriptParser.EqExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>andExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpr([NotNull] DesignScriptParser.AndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>andExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpr([NotNull] DesignScriptParser.AndExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>orExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrExpr([NotNull] DesignScriptParser.OrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>orExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrExpr([NotNull] DesignScriptParser.OrExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>triRangeExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTriRangeExpr([NotNull] DesignScriptParser.TriRangeExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>triRangeExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTriRangeExpr([NotNull] DesignScriptParser.TriRangeExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>unitRangeExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnitRangeExpr([NotNull] DesignScriptParser.UnitRangeExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>unitRangeExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnitRangeExpr([NotNull] DesignScriptParser.UnitRangeExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>inlineConditionExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInlineConditionExpr([NotNull] DesignScriptParser.InlineConditionExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>inlineConditionExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInlineConditionExpr([NotNull] DesignScriptParser.InlineConditionExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>parenExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenExpr([NotNull] DesignScriptParser.ParenExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>parenExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenExpr([NotNull] DesignScriptParser.ParenExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>litExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLitExpr([NotNull] DesignScriptParser.LitExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>litExpr</c>
	/// labeled alternative in <see cref="DesignScriptParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLitExpr([NotNull] DesignScriptParser.LitExprContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>ident</c>
	/// labeled alternative in <see cref="DesignScriptParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdent([NotNull] DesignScriptParser.IdentContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ident</c>
	/// labeled alternative in <see cref="DesignScriptParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdent([NotNull] DesignScriptParser.IdentContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>doubleLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoubleLit([NotNull] DesignScriptParser.DoubleLitContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>doubleLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoubleLit([NotNull] DesignScriptParser.DoubleLitContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>intLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntLit([NotNull] DesignScriptParser.IntLitContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>intLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntLit([NotNull] DesignScriptParser.IntLitContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>stringLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringLit([NotNull] DesignScriptParser.StringLitContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stringLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringLit([NotNull] DesignScriptParser.StringLitContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>boolLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolLit([NotNull] DesignScriptParser.BoolLitContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>boolLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolLit([NotNull] DesignScriptParser.BoolLitContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>nullLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNullLit([NotNull] DesignScriptParser.NullLitContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>nullLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNullLit([NotNull] DesignScriptParser.NullLitContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>listLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterListLit([NotNull] DesignScriptParser.ListLitContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>listLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitListLit([NotNull] DesignScriptParser.ListLitContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>dictLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDictLit([NotNull] DesignScriptParser.DictLitContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>dictLit</c>
	/// labeled alternative in <see cref="DesignScriptParser.lit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDictLit([NotNull] DesignScriptParser.DictLitContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>imperCoreStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImperCoreStmt([NotNull] DesignScriptParser.ImperCoreStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>imperCoreStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImperCoreStmt([NotNull] DesignScriptParser.ImperCoreStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>ifStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStmt([NotNull] DesignScriptParser.IfStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ifStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStmt([NotNull] DesignScriptParser.IfStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>forStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStmt([NotNull] DesignScriptParser.ForStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>forStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStmt([NotNull] DesignScriptParser.ForStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>whileStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStmt([NotNull] DesignScriptParser.WhileStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>whileStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStmt([NotNull] DesignScriptParser.WhileStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>breakStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreakStmt([NotNull] DesignScriptParser.BreakStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>breakStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreakStmt([NotNull] DesignScriptParser.BreakStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>continueStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContinueStmt([NotNull] DesignScriptParser.ContinueStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>continueStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContinueStmt([NotNull] DesignScriptParser.ContinueStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>blockStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockStmt([NotNull] DesignScriptParser.BlockStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>blockStmt</c>
	/// labeled alternative in <see cref="DesignScriptParser.imperStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockStmt([NotNull] DesignScriptParser.BlockStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>typeNameArbitraryRank</c>
	/// labeled alternative in <see cref="DesignScriptParser.typeNameWithRank"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeNameArbitraryRank([NotNull] DesignScriptParser.TypeNameArbitraryRankContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>typeNameArbitraryRank</c>
	/// labeled alternative in <see cref="DesignScriptParser.typeNameWithRank"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeNameArbitraryRank([NotNull] DesignScriptParser.TypeNameArbitraryRankContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>typeNameRankOneOrMore</c>
	/// labeled alternative in <see cref="DesignScriptParser.typeNameWithRank"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeNameRankOneOrMore([NotNull] DesignScriptParser.TypeNameRankOneOrMoreContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>typeNameRankOneOrMore</c>
	/// labeled alternative in <see cref="DesignScriptParser.typeNameWithRank"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeNameRankOneOrMore([NotNull] DesignScriptParser.TypeNameRankOneOrMoreContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>typeNameRank</c>
	/// labeled alternative in <see cref="DesignScriptParser.typeNameWithRank"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeNameRank([NotNull] DesignScriptParser.TypeNameRankContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>typeNameRank</c>
	/// labeled alternative in <see cref="DesignScriptParser.typeNameWithRank"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeNameRank([NotNull] DesignScriptParser.TypeNameRankContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] DesignScriptParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] DesignScriptParser.ProgramContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.coreStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCoreStmt([NotNull] DesignScriptParser.CoreStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.coreStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCoreStmt([NotNull] DesignScriptParser.CoreStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.funcDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncDef([NotNull] DesignScriptParser.FuncDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.funcDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncDef([NotNull] DesignScriptParser.FuncDefContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.imperFuncDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImperFuncDef([NotNull] DesignScriptParser.ImperFuncDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.imperFuncDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImperFuncDef([NotNull] DesignScriptParser.ImperFuncDefContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.emptyStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmptyStmt([NotNull] DesignScriptParser.EmptyStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.emptyStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmptyStmt([NotNull] DesignScriptParser.EmptyStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.funcDefArgList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncDefArgList([NotNull] DesignScriptParser.FuncDefArgListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.funcDefArgList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncDefArgList([NotNull] DesignScriptParser.FuncDefArgListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.funcDefArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncDefArg([NotNull] DesignScriptParser.FuncDefArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.funcDefArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncDefArg([NotNull] DesignScriptParser.FuncDefArgContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] DesignScriptParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] DesignScriptParser.ExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimary([NotNull] DesignScriptParser.PrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimary([NotNull] DesignScriptParser.PrimaryContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.parExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParExpr([NotNull] DesignScriptParser.ParExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.parExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParExpr([NotNull] DesignScriptParser.ParExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.lit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLit([NotNull] DesignScriptParser.LitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.lit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLit([NotNull] DesignScriptParser.LitContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.exprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprList([NotNull] DesignScriptParser.ExprListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.exprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprList([NotNull] DesignScriptParser.ExprListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.atLevel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtLevel([NotNull] DesignScriptParser.AtLevelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.atLevel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtLevel([NotNull] DesignScriptParser.AtLevelContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.repGuideList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepGuideList([NotNull] DesignScriptParser.RepGuideListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.repGuideList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepGuideList([NotNull] DesignScriptParser.RepGuideListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.exprStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprStmt([NotNull] DesignScriptParser.ExprStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.exprStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprStmt([NotNull] DesignScriptParser.ExprStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStmt([NotNull] DesignScriptParser.ReturnStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStmt([NotNull] DesignScriptParser.ReturnStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.imperAnnot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImperAnnot([NotNull] DesignScriptParser.ImperAnnotContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.imperAnnot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImperAnnot([NotNull] DesignScriptParser.ImperAnnotContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.imperBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImperBlock([NotNull] DesignScriptParser.ImperBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.imperBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImperBlock([NotNull] DesignScriptParser.ImperBlockContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.imperBlockReturnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImperBlockReturnStmt([NotNull] DesignScriptParser.ImperBlockReturnStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.imperBlockReturnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImperBlockReturnStmt([NotNull] DesignScriptParser.ImperBlockReturnStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.imperBlockAssignStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImperBlockAssignStmt([NotNull] DesignScriptParser.ImperBlockAssignStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.imperBlockAssignStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImperBlockAssignStmt([NotNull] DesignScriptParser.ImperBlockAssignStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.imperBlockBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImperBlockBody([NotNull] DesignScriptParser.ImperBlockBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.imperBlockBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImperBlockBody([NotNull] DesignScriptParser.ImperBlockBodyContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.imperStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImperStmt([NotNull] DesignScriptParser.ImperStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.imperStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImperStmt([NotNull] DesignScriptParser.ImperStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.assignStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignStmt([NotNull] DesignScriptParser.AssignStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.assignStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignStmt([NotNull] DesignScriptParser.AssignStmtContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.typedIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypedIdent([NotNull] DesignScriptParser.TypedIdentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.typedIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypedIdent([NotNull] DesignScriptParser.TypedIdentContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.keyValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyValue([NotNull] DesignScriptParser.KeyValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.keyValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyValue([NotNull] DesignScriptParser.KeyValueContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.keyValues"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyValues([NotNull] DesignScriptParser.KeyValuesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.keyValues"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyValues([NotNull] DesignScriptParser.KeyValuesContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.typedIdentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypedIdentList([NotNull] DesignScriptParser.TypedIdentListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.typedIdentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypedIdentList([NotNull] DesignScriptParser.TypedIdentListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.identList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentList([NotNull] DesignScriptParser.IdentListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.identList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentList([NotNull] DesignScriptParser.IdentListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.qualifiedIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQualifiedIdent([NotNull] DesignScriptParser.QualifiedIdentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.qualifiedIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQualifiedIdent([NotNull] DesignScriptParser.QualifiedIdentContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.typeNameWithRank"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeNameWithRank([NotNull] DesignScriptParser.TypeNameWithRankContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.typeNameWithRank"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeNameWithRank([NotNull] DesignScriptParser.TypeNameWithRankContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="DesignScriptParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeName([NotNull] DesignScriptParser.TypeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DesignScriptParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeName([NotNull] DesignScriptParser.TypeNameContext context);
}
} // namespace LlvmDSCompiler
